// examples/vue-demo/src/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import {
  useJalaliDate,
  useMobileNumber,
  useNationalCode,
  useNumberWords,
  usePersianDigits,
} from "vite-plugin-persian/vue";
import { formatCurrency, normalizePersianText, toEnglishDigits, toToman } from "virtual:persian/text";

const amount = ref("12500000");
const rial = computed(() => Number(toEnglishDigits(amount.value).replace(/\D+/g, "")) || 0);
const toman = computed(() => toToman(rial.value));
const rialFmt = computed(() => formatCurrency(rial.value, { unit: "ریال" }));
const tomanFmt = computed(() => formatCurrency(toman.value));
const tomanEn = computed(() => formatCurrency(toman.value, { unit: "تومان", digits: "english" }));

const nationalCode = ref("0010042911");
const mobile = ref("09123456789");
const number = ref(12500);

const codeValid = useNationalCode(nationalCode);
const mobileValid = useMobileNumber(mobile);
const words = useNumberWords(number);

const now = ref(new Date());
const jalali = useJalaliDate(now, "d MMMM YYYY");
const timeText = computed(() => usePersianDigits(now.value.toLocaleTimeString("en-GB")));

let timer: ReturnType<typeof setInterval> | undefined;
onMounted(() => {
  timer = setInterval(() => (now.value = new Date()), 1000);
});
onUnmounted(() => clearInterval(timer));
</script>

<template>
  <main class="app" lang="fa" dir="rtl">
    <h1>vite-plugin-persian · Vue</h1>
    <p class="tagline">
      Uses <code>vite-plugin-persian/vue</code>, the global <code>v-persian-digits</code>
      directive, and <code>useJalaliDate</code> for the live clock.
    </p>

    <section class="card">
      <h2>Currency — Rial ↔ Toman</h2>
      <input v-model="amount" inputmode="numeric" aria-label="Amount in Rial" />
      <ul>
        <li>Rial (fa): <strong>{{ rialFmt }}</strong></li>
        <li>Toman (fa): <strong>{{ tomanFmt }}</strong></li>
        <li>Toman (en): <strong>{{ tomanEn }}</strong></li>
      </ul>
      <p>
        Directive output: <span v-persian-digits="rial">0</span>
      </p>
    </section>

    <section class="card">
      <h2>Live validation &amp; words</h2>
      <label>
        کد ملی
        <input v-model="nationalCode" />
        <span :class="codeValid ? 'ok' : 'bad'">{{ codeValid ? 'معتبر' : 'نامعتبر' }}</span>
      </label>
      <label>
        موبایل
        <input v-model="mobile" />
        <span :class="mobileValid ? 'ok' : 'bad'">{{ mobileValid ? 'معتبر' : 'نامعتبر' }}</span>
      </label>
      <label>
        Number
        <input v-model.number="number" type="number" inputmode="numeric" />
      </label>
      <p class="words">{{ words }}</p>
      <p>Normalized text: <em>{{ normalizePersianText('يك   تست  ميباشد') }}</em></p>
    </section>

    <section class="card">
      <h2>Jalali calendar</h2>
      <p class="big">{{ jalali }}</p>
      <p class="time">{{ timeText }}</p>
    </section>
  </main>
</template>

// examples/react-demo/src/App.tsx
import { useEffect, useState } from "react";
import {
  formatCurrency,
  toPersianDigits,
  toRial,
  toToman,
  useJalaliDate,
  useMobileNumber,
  useNationalCode,
  useNumberWords,
  usePersianDigits,
} from "vite-plugin-persian/react";
import { normalizePersianText } from "virtual:persian/text";

function useNow(intervalMs: number): Date {
  const [now, setNow] = useState(() => new Date());
  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), intervalMs);
    return () => clearInterval(id);
  }, [intervalMs]);
  return now;
}

function CurrencyCard() {
  const [amount, setAmount] = useState("12500000");
  const rial = Number(amount.replace(/[^\d]/g, "")) || 0;
  const toman = toToman(rial);

  return (
    <section className="card">
      <h2>Currency — Rial ↔ Toman</h2>
      <input
        inputMode="numeric"
        value={amount}
        onChange={(event) => setAmount(event.target.value)}
        aria-label="Amount in Rial"
      />
      <ul>
        <li>
          Rial (fa): <strong>{formatCurrency(rial, { unit: "ریال" })}</strong>
        </li>
        <li>
          Toman (fa): <strong>{formatCurrency(toman)}</strong>
        </li>
        <li>
          Toman (en):{" "}
          <strong>{formatCurrency(toman, { unit: "تومان", digits: "english" })}</strong>
        </li>
        <li>
          Round-trip: <code>toRial(1000)</code> → <strong>{toPersianDigits(toRial(1000))}</strong>
        </li>
      </ul>
    </section>
  );
}

function ValidationCard() {
  const [nationalCode, setNationalCode] = useState("0010042911");
  const [mobile, setMobile] = useState("09123456789");
  const [amount, setAmount] = useState(12500);

  const codeValid = useNationalCode(nationalCode);
  const mobileValid = useMobileNumber(mobile);
  const words = useNumberWords(amount);

  return (
    <section className="card">
      <h2>Live validation &amp; words</h2>
      <label>
        کد ملی
        <input value={nationalCode} onChange={(event) => setNationalCode(event.target.value)} />
        <span className={codeValid ? "ok" : "bad"}>{codeValid ? "معتبر" : "نامعتبر"}</span>
      </label>
      <label>
        موبایل
        <input value={mobile} onChange={(event) => setMobile(event.target.value)} />
        <span className={mobileValid ? "ok" : "bad"}>{mobileValid ? "معتبر" : "نامعتبر"}</span>
      </label>
      <label>
        Number
        <input
          type="number"
          inputMode="numeric"
          value={amount}
          onChange={(event) => setAmount(Number(event.target.value))}
        />
      </label>
      <p className="words">{words}</p>
      <p>
        Normalized text: <em>{normalizePersianText("يك   تست  ميباشد")}</em>
      </p>
    </section>
  );
}

function JalaliClockCard() {
  const now = useNow(1000);
  const jalali = useJalaliDate(now, "d MMMM YYYY");
  const time = usePersianDigits(now.toLocaleTimeString("en-GB"));

  return (
    <section className="card">
      <h2>Jalali calendar</h2>
      <p className="big">{jalali}</p>
      <p className="time">{time}</p>
    </section>
  );
}

export default function App() {
  return (
    <main className="app" lang="fa" dir="rtl">
      <h1>vite-plugin-persian · React</h1>
      <p className="tagline">
        Uses <code>vite-plugin-persian/react</code>, the virtual modules, and{" "}
        <code>useJalaliDate</code> for the live clock.
      </p>
      <CurrencyCard />
      <ValidationCard />
      <JalaliClockCard />
    </main>
  );
}
